[[rulesets]]
group = "🤖 AI"
ruleset = "https://raw.githubusercontent.com/0honus0/SubconverterRule/master/Ai.list"

[[rulesets]]
group = "🔰 节点选择"
ruleset = "https://raw.githubusercontent.com/0honus0/SubconverterRule/master/Proxy.list"

# Telegram
[[rulesets]]
group = "🔰 节点选择"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list"

# Github
[[rulesets]]
group = "🔰 节点选择"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.list"

# Google
[[rulesets]]
group = "🔰 节点选择"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Google/Google.list"

# Steam
[[rulesets]]
group = "🔰 节点选择"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Steam/Steam.list"

[[rulesets]]
group = "🎯 全球直连"
ruleset = "https://raw.githubusercontent.com/0honus0/SubconverterRule/master/Direct.list"

[[rulesets]]
group = "🎯 全球直连"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/ChinaDomain.list"

[[rulesets]]
group = "🎯 全球直连"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/ChinaMedia.list"

[[rulesets]]
group = "🎯 全球直连"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list"

[[rulesets]]
group = "🎯 全球直连"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list"

[[rulesets]]
group = "🎯 全球直连"
ruleset = "https://raw.githubusercontent.com/NobyDa/Script/master/Surge/WeChat.list"

[[rulesets]]
group = "🎯 全球直连"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "👤 OWN"
ruleset = "https://raw.githubusercontent.com/0honus0/SubconverterRule/master/Own.list"

[[rulesets]]
group = "🌍 国外媒体"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTubeMusic/YouTubeMusic.list"

[[rulesets]]
group = "🌍 国外媒体"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Netflix/Netflix.list"

[[rulesets]]
group = "🌍 国外媒体"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTube/YouTube.list"

[[rulesets]]
group = "Ⓜ️ 微软服务"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list"

[[rulesets]]
group = "🍎 苹果服务"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list"

[[rulesets]]
group = "🛑 全球拦截"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list"

[[rulesets]]
group = "🛑 全球拦截"
ruleset = "https://raw.githubusercontent.com/0honus0/SubconverterRule/master/Reject"

[[rulesets]]
group = "🐟 漏网之鱼"
ruleset = "[]FINAL"

# [[rulesets]]
# group = "🎥 NETFLIX"
# ruleset = "rules/DivineEngine/Surge/Ruleset/StreamingMedia/Video/Netflix.list"

# [[rulesets]]
# group = "🌏 国内媒体"
# ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list"
